---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
    - "**/vim/plugged/**/*"
    - "**/vim/undo/**/*"
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
