" set ft=vim
" Get rid of the macvim and gvim toolbars
set go-=T
set go-=m

" disable middle click pasting (I accidentally do this all the time)
nnoremap <MiddleMouse>   <Nop>
nnoremap <2-MiddleMouse> <Nop>
nnoremap <3-MiddleMouse> <Nop>
nnoremap <4-MiddleMouse> <Nop>

inoremap <MiddleMouse>   <Nop>
inoremap <2-MiddleMouse> <Nop>
inoremap <3-MiddleMouse> <Nop>
inoremap <4-MiddleMouse> <Nop>

if has('gui_macvim')
  set guifont=Inconsolata:h18
  macm Window.Select\ Previous\ Tab  key=<D-Left>
  macm Window.Select\ Next\ Tab	     key=<D-Right>
endif
