" Legacy Vim fallback.
" Neovim is configured in vim/init.lua.

set nocompatible

syntax on
filetype plugin indent on

set clipboard+=unnamedplus

set termencoding=utf-8
set encoding=utf-8

set hidden
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set number
set autoread

set ignorecase
set smartcase
set showmatch
set hlsearch
set incsearch
set gdefault

set nobackup
set nowritebackup
set noswapfile
set nomodeline
set mouse=a

let mapleader = ","

nnoremap j gj
nnoremap k gk
nnoremap ; :
nnoremap <leader><space> :noh<cr>
cnoreabbrev W w
nnoremap Q <Nop>

if has("persistent_undo")
  set undofile
  set undodir=$HOME/.vim/undo
  set undolevels=1000
  set undoreload=10000
endif

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+\%#\@<!$/
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red

function! s:StripTrailingWhitespaces() abort
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfunction

augroup strip_trailing_whitespace
  autocmd!
  autocmd BufWritePre * if &ft!~?'markdown' | call <SID>StripTrailingWhitespaces() | endif
augroup END
