#!/bin/sh

set -eu

lint_tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/dotfiles-lint-shell.XXXXXX")
trap 'rm -rf "$lint_tmp_dir"' EXIT HUP INT TERM

shfmt -f . > "$lint_tmp_dir/all-shell-files"
awk '!/^(node_modules\/|vim\/)/ && !/\.zsh$/' \
  "$lint_tmp_dir/all-shell-files" > "$lint_tmp_dir/shellcheck-files"

while IFS= read -r shell_file; do
  shellcheck -x "$shell_file"
done < "$lint_tmp_dir/shellcheck-files"

find . \( -path './.git' -o -path './node_modules' -o -path './vim' \) -prune \
  -o -type f -name '*.zsh' -exec zsh -n {} +
