#!/usr/bin/env bash

if [ ! -d "$1" ]; then
  echo "$1 is not a directory"
  exit 1
else
  target="$1"
  cd "$target"
fi

function rename_files_with_extension
{
  extension="$1"
  for file in *.$extension
  do
    if [ -f "$file" ];then
      newfile=$(openssl sha1 "$file" | awk '{print $2}' | base64)
      echo $newfile
      mv "$file" "$newfile.$extension"
    fi
  done
}

set -o xtrace
rename_files_with_extension "png"
rename_files_with_extension "gif"
rename_files_with_extension "jpg"
rename_files_with_extension "jpeg"


