# vim: filetype=zsh

# =========================================================================== #
# Homebrew setup                                                              #
# =========================================================================== #

# Disable Homebrew auto-update only during shell startup so `brew shellenv` cannot
# trigger network work when opening a terminal on unreliable connections.
export HOMEBREW_NO_AUTO_UPDATE=1

# Disable Homebrew analytics for every shell; this avoids background reporting
# without changing normal install, upgrade, or update behavior.
export HOMEBREW_NO_ANALYTICS=1

if [ -f /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv zsh)"
  # Must be set before compinit
  FPATH="${HOMEBREW_PREFIX}/share/zsh/site-functions:${FPATH}"
fi

# Re-enable Homebrew auto-update for normal `brew install`/`brew upgrade` usage.
unset HOMEBREW_NO_AUTO_UPDATE

# =========================================================================== #
# Docker Desktop setup                                                        #
# =========================================================================== #

# Docker completions are generated by `make completions`.
completions="$HOME/.docker/completions"
if [[ -f $completions/_docker ]]; then
  FPATH="$completions:$FPATH"
fi

# =========================================================================== #
# Useful shell functions                                                      #
# =========================================================================== #

# Change the current directory to the frontmost window of Finder.app.
cdf() {
  local -r finder="$(
    osascript \
      -e 'tell application "Finder"' \
      -e 'set myname to POSIX path of (target of window 1 as alias)' \
      -e 'end tell' \
      2> /dev/null
  )"

  cd "$finder" || return 1
}

# Create a temporary and ephemeral Chrome instance.
#
# This function launches a new, separate Chrome instance with a temporary
# profile in incognito mode.
#
# This function will block until the new Chrome instance is quit.
wipe() {
  local -r profile="$(mktemp -d)"
  local -r chrome_args=(
    --disable-bundled-ppapi-flash --disable-offline-load-stale-cache
    --disk-cache-size=1 --media-cache-size=1 --disk-cache-dir=/dev/null
    --no-first-run --no-referrers --no-default-browser-check
    --new-window --incognito --user-data-dir="${profile}"
  )

  {
    open -a "Google Chrome" -nW --args "${chrome_args[@]}"
  } always {
    rm -rf -- "$profile"
  }
}

# =========================================================================== #
# Tool managers                                                               #
# =========================================================================== #

path=("$HOME/.local/bin" $path)

if command -v mise > /dev/null; then
  eval "$(mise activate zsh)"
fi

# =========================================================================== #
# Tools                                                                       #
# =========================================================================== #

alias nosleeptillbrooklyn='caffeinate -s'
alias listening_ports='sudo lsof -PiTCP -sTCP:LISTEN'

# Avoid defining the `CLICOLOR` env variable to get colorized `ls` output on
# macOS. `-G` is equivalent to `CLICOLOR=1` and `--color=auto`. See `man ls`.
#
# `-h` uses human size suffixes in combination with `-l`.
# `-F` displays markers for directories for executables, directories, and
# symlinks.
alias ls="ls -G -h -F"

# =========================================================================== #
# Prompt                                                                      #
# =========================================================================== #

if command -v starship > /dev/null; then
  eval "$(starship init zsh)"
fi
