---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * WED"
jobs:
  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"

      - name: Install gems
        run: bundle install

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop

  shell:
    name: Lint and format shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Format shell sources with shfmt
        uses: docker://mvdan/shfmt
        with:
          entrypoint: /bin/shfmt
          args: -i 2 -ci -s -d /github/workspace

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Format with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          sudo -H python3 -m pip install --upgrade pip setuptools wheel
          sudo -H python3 -m pip install --upgrade yamllint
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict .
          echo "OK"
